//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ironclad.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbLogAll {
            get {
                return ((bool)(this["cbLogAll"]));
            }
            set {
                this["cbLogAll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbWindowed {
            get {
                return ((bool)(this["cbWindowed"]));
            }
            set {
                this["cbWindowed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbMuted {
            get {
                return ((bool)(this["cbMuted"]));
            }
            set {
                this["cbMuted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbLaunch {
            get {
                return ((bool)(this["cbLaunch"]));
            }
            set {
                this["cbLaunch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbValidateUnitModels {
            get {
                return ((bool)(this["cbValidateUnitModels"]));
            }
            set {
                this["cbValidateUnitModels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbValidateOtherFiles {
            get {
                return ((bool)(this["cbValidateOtherFiles"]));
            }
            set {
                this["cbValidateOtherFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbShowStatsFactions {
            get {
                return ((bool)(this["cbShowStatsFactions"]));
            }
            set {
                this["cbShowStatsFactions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbShowStatsRegions {
            get {
                return ((bool)(this["cbShowStatsRegions"]));
            }
            set {
                this["cbShowStatsRegions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbShowStatsResources {
            get {
                return ((bool)(this["cbShowStatsResources"]));
            }
            set {
                this["cbShowStatsResources"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbShowStatsScripts {
            get {
                return ((bool)(this["cbShowStatsScripts"]));
            }
            set {
                this["cbShowStatsScripts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbShowStatsNamesets {
            get {
                return ((bool)(this["cbShowStatsNamesets"]));
            }
            set {
                this["cbShowStatsNamesets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ResolutionIndex {
            get {
                return ((int)(this["ResolutionIndex"]));
            }
            set {
                this["ResolutionIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbBattleAI {
            get {
                return ((bool)(this["cbBattleAI"]));
            }
            set {
                this["cbBattleAI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbColonies {
            get {
                return ((bool)(this["cbColonies"]));
            }
            set {
                this["cbColonies"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbCouncil {
            get {
                return ((bool)(this["cbCouncil"]));
            }
            set {
                this["cbCouncil"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbAIExpansion {
            get {
                return ((bool)(this["cbAIExpansion"]));
            }
            set {
                this["cbAIExpansion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbForcedMarch {
            get {
                return ((bool)(this["cbForcedMarch"]));
            }
            set {
                this["cbForcedMarch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbBlockades {
            get {
                return ((bool)(this["cbBlockades"]));
            }
            set {
                this["cbBlockades"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbInformants {
            get {
                return ((bool)(this["cbInformants"]));
            }
            set {
                this["cbInformants"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbGarrisons {
            get {
                return ((bool)(this["cbGarrisons"]));
            }
            set {
                this["cbGarrisons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbReligiousUnrest {
            get {
                return ((bool)(this["cbReligiousUnrest"]));
            }
            set {
                this["cbReligiousUnrest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbAutonomies {
            get {
                return ((bool)(this["cbAutonomies"]));
            }
            set {
                this["cbAutonomies"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbMobilization {
            get {
                return ((bool)(this["cbMobilization"]));
            }
            set {
                this["cbMobilization"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbConsumables {
            get {
                return ((bool)(this["cbConsumables"]));
            }
            set {
                this["cbConsumables"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbSiegeCosts {
            get {
                return ((bool)(this["cbSiegeCosts"]));
            }
            set {
                this["cbSiegeCosts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbExpansionPenalty {
            get {
                return ((bool)(this["cbExpansionPenalty"]));
            }
            set {
                this["cbExpansionPenalty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbSelectHeir {
            get {
                return ((bool)(this["cbSelectHeir"]));
            }
            set {
                this["cbSelectHeir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbDiplomacyCosts {
            get {
                return ((bool)(this["cbDiplomacyCosts"]));
            }
            set {
                this["cbDiplomacyCosts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbSiegeRestriction {
            get {
                return ((bool)(this["cbSiegeRestriction"]));
            }
            set {
                this["cbSiegeRestriction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbCapitalChange {
            get {
                return ((bool)(this["cbCapitalChange"]));
            }
            set {
                this["cbCapitalChange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbCapitalLost {
            get {
                return ((bool)(this["cbCapitalLost"]));
            }
            set {
                this["cbCapitalLost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbDebtCrises {
            get {
                return ((bool)(this["cbDebtCrises"]));
            }
            set {
                this["cbDebtCrises"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbInvasions {
            get {
                return ((bool)(this["cbInvasions"]));
            }
            set {
                this["cbInvasions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbPeaceseeking {
            get {
                return ((bool)(this["cbPeaceseeking"]));
            }
            set {
                this["cbPeaceseeking"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbReEmergence {
            get {
                return ((bool)(this["cbReEmergence"]));
            }
            set {
                this["cbReEmergence"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbRegulation {
            get {
                return ((bool)(this["cbRegulation"]));
            }
            set {
                this["cbRegulation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbCivilWars {
            get {
                return ((bool)(this["cbCivilWars"]));
            }
            set {
                this["cbCivilWars"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbDeals {
            get {
                return ((bool)(this["cbDeals"]));
            }
            set {
                this["cbDeals"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbRaids {
            get {
                return ((bool)(this["cbRaids"]));
            }
            set {
                this["cbRaids"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbSeaLoot {
            get {
                return ((bool)(this["cbSeaLoot"]));
            }
            set {
                this["cbSeaLoot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbLoot {
            get {
                return ((bool)(this["cbLoot"]));
            }
            set {
                this["cbLoot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbEmergencyTaxes {
            get {
                return ((bool)(this["cbEmergencyTaxes"]));
            }
            set {
                this["cbEmergencyTaxes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbLoans {
            get {
                return ((bool)(this["cbLoans"]));
            }
            set {
                this["cbLoans"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbEmpire {
            get {
                return ((bool)(this["cbEmpire"]));
            }
            set {
                this["cbEmpire"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbFirstTimeBuild {
            get {
                return ((bool)(this["cbFirstTimeBuild"]));
            }
            set {
                this["cbFirstTimeBuild"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbRNGE {
            get {
                return ((bool)(this["cbRNGE"]));
            }
            set {
                this["cbRNGE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbFirstContact {
            get {
                return ((bool)(this["cbFirstContact"]));
            }
            set {
                this["cbFirstContact"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbRazing {
            get {
                return ((bool)(this["cbRazing"]));
            }
            set {
                this["cbRazing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbMigration {
            get {
                return ((bool)(this["cbMigration"]));
            }
            set {
                this["cbMigration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbAlliedAssist {
            get {
                return ((bool)(this["cbAlliedAssist"]));
            }
            set {
                this["cbAlliedAssist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbUnification {
            get {
                return ((bool)(this["cbUnification"]));
            }
            set {
                this["cbUnification"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbAICapitalBoost {
            get {
                return ((bool)(this["cbAICapitalBoost"]));
            }
            set {
                this["cbAICapitalBoost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbSlaveSpawnUnits {
            get {
                return ((bool)(this["cbSlaveSpawnUnits"]));
            }
            set {
                this["cbSlaveSpawnUnits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbEventSpawns {
            get {
                return ((bool)(this["cbEventSpawns"]));
            }
            set {
                this["cbEventSpawns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\Steam\\steamapps\\common\\Medieval II Total War\\medieval2.exe" +
            "")]
        public string GameExeFullpath {
            get {
                return ((string)(this["GameExeFullpath"]));
            }
            set {
                this["GameExeFullpath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FeatureCount {
            get {
                return ((int)(this["FeatureCount"]));
            }
            set {
                this["FeatureCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbAIRecruitmentBoost {
            get {
                return ((bool)(this["cbAIRecruitmentBoost"]));
            }
            set {
                this["cbAIRecruitmentBoost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbPopeMechanics {
            get {
                return ((bool)(this["cbPopeMechanics"]));
            }
            set {
                this["cbPopeMechanics"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cbRoadTest {
            get {
                return ((bool)(this["cbRoadTest"]));
            }
            set {
                this["cbRoadTest"] = value;
            }
        }
    }
}
